#Store all the constants over here

errNO = {\
	'SUCCESS':0\
	,'FILE_NOT_FOUND':-1\
	,'INDEX_OUT_OF_BOUND':-2\
	,'DUMMY':1\
}

SEC_START_TIME = '2015-01-01 00:00:00'
SEC_COL_NAME = 'Seconds'
MMSI_COL_NAME = "MMSI"
BASE_TIME_COL_NAME = 'BaseDateTime'
LAT_COL_NAME = "LAT"
LON_COL_NAME = "LON"
SOG_COL_NAME = "SOG"
COG_COL_NAME = "COG"
HEADING_COL_NAME = "Heading"
VESSEL_NAME_COL_NAME = "VesselName"
IMO_COL_NAME = "IMO"
CALL_SIGN_COL_NAME = "CallSign"
VESSEL_TYPE_COL_NAME = "VesselType"
STATUS_COL_NAME = "Status"
LENGTH_COL_NAME = "Length"
WIDTH_COL_NAME = "Width"
DRAFT_COL_NAME = "Draft"
CARGO_COL_NAME = "Cargo"
TOTAL_DISTANCE_COL_NAME = "TotalDistance"
ANGLE_COL_NAME = "Angle"